name: bluebellapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  flutter_native_timezone: ^1.0.4
  cupertino_icons: ^0.1.2
  #flutter_secure_storage: ^3.3.1+1
  progress_dialog: ^1.2.2
  curved_navigation_bar: ^0.3.2
  flutter_html: ^0.11.1
  mask_text_input_formatter: ^1.0.6
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  url_launcher: ^5.1.3
  get_it: ^4.0.1
  #intl: ^0.16.1
  transparent_image: ^1.0.0
  cached_network_image: ^2.2.0+1
  smooth_star_rating: ^1.0.3
  http: ^0.12.0+2
  font_awesome_flutter: ^8.8.1
  # flutter_secure_storage: ^3.3.1+1
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.3.0"
  pin_entry_text_field: ^0.1.4
  google_fonts: ^0.3.9
  flutter_launcher_icons: "^0.7.3"
  carousel_slider: ^2.1.0
  calendar_strip: ^1.0.7
  #calendar_strip: ^1.0.4
  #table_calendar: ^2.2.3
  sliding_up_panel: ^1.0.2
  email_validator: '^1.0.0'
  fluttertoast: ^7.0.1  
  toast: ^0.1.5
  responsive_framework: ^0.0.7
  flutter_page_indicator: ^0.0.3
  clippy_flutter: ^1.1.0
  # flutter_svg: ^0.18.0
  keyboard_avoider: ^0.1.2
  flutter_pagewise: ^1.2.3
  keyboard_visibility: ^0.5.6
  flutter_statusbarcolor: ^0.2.3
  path_provider: ^1.6.17
  flutter_device_type: ^0.2.0
  # webview_flutter: ^1.0.1
  # flutter_webview_plugin: ^0.3.11
  flutter_inappwebview: ^4.0.0+4
  reflectable: ^2.2.8
  photo_view: ^0.9.2
  gallery_view: ^0.0.4
  new_version: ^0.0.5
  #admob_flutter: ^1.0.1
  #full_screen_image: ^1.0.2
  fluro: ^1.7.7
  sqflite: ^1.3.2+1
  flutter_swiper: ^1.1.6
  percent_indicator: ^2.1.8
  flutter_animation_progress_bar: ^1.0.6
  icon_shadow: ^1.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/android-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/landscape/
    - assets/images/icons/
  


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/sf-ui-display-light.otf
